function go(id){const e=document.getElementById(id);if(e)e.scrollIntoView({behavior:'smooth'})}
function nc(e,id){e.preventDefault();go(id)}
function mnc(e,id){e.preventDefault();closeMM();go(id)}
window.addEventListener('scroll',()=>{document.getElementById('nav').classList.toggle('scr',scrollY>20)},{passive:true})
let mmOpen=false
function togMM(){mmOpen=!mmOpen;document.getElementById('mm').classList.toggle('open',mmOpen);const b=document.getElementById('ntgb');b.innerHTML=mmOpen?'<i data-lucide="x" style="width:22px;height:22px"></i>':'<i data-lucide="menu" style="width:22px;height:22px"></i>';lucide.createIcons()}
function closeMM(){mmOpen=false;document.getElementById('mm').classList.remove('open');document.getElementById('ntgb').innerHTML='<i data-lucide="menu" style="width:22px;height:22px"></i>';lucide.createIcons()}
const KU='iiitbhopal_user',KS='iiitbhopal_users'
function getU(){try{return JSON.parse(localStorage.getItem(KU))}catch{return null}}
function getUs(){try{return JSON.parse(localStorage.getItem(KS))||[]}catch{return[]}}
function saveUs(u){localStorage.setItem(KS,JSON.stringify(u))}
function saveU(u){u?localStorage.setItem(KU,JSON.stringify(u)):localStorage.removeItem(KU)}
function updNav(u){const na=document.getElementById('na'),nu=document.getElementById('nu'),ma=document.getElementById('mma'),mu=document.getElementById('mmu');if(u){na.style.display='none';nu.style.display='flex';ma.style.display='none';mu.style.display='flex';const i=u.name.charAt(0).toUpperCase(),nm=u.name.length>12?u.name.slice(0,12)+'\u2026':u.name;document.getElementById('navi').textContent=i;document.getElementById('navt').textContent=nm;document.getElementById('mavi').textContent=i;document.getElementById('mavt').textContent=nm}else{na.style.display='flex';nu.style.display='none';ma.style.display='flex';mu.style.display='none'}}
function doLogout(){saveU(null);updNav(null);toast('You have been logged out.','ok')}
updNav(getU())
function openModal(tab){swTab(tab);document.getElementById('modal').classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){document.getElementById('modal').classList.remove('open');document.body.style.overflow='';clearErr();document.querySelectorAll('#modal form').forEach(f=>f.reset())}
function closeOut(e){if(e.target===document.getElementById('modal'))closeModal()}
function swTab(t){document.getElementById('pl').classList.toggle('act',t==='login');document.getElementById('pr').classList.toggle('act',t==='reg');document.getElementById('tl').classList.toggle('act',t==='login');document.getElementById('tr').classList.toggle('act',t==='reg')}
function clearErr(){['lerr','rerr'].forEach(id=>{const e=document.getElementById(id);e.style.display='none';e.textContent=''})}
function showErr(id,m){const e=document.getElementById(id);e.textContent=m;e.style.display='block'}
function doLogin(e){e.preventDefault();const em=document.getElementById('le').value.trim(),pw=document.getElementById('lp').value,b=document.getElementById('lbtn');if(!em||!pw){showErr('lerr','Please fill in all fields.');return}b.textContent='Logging in...';setTimeout(()=>{const f=getUs().find(u=>u.email.toLowerCase()===em.toLowerCase()&&u.password===pw);b.textContent='Login';if(f){const u={name:f.name,email:f.email};saveU(u);updNav(u);closeModal();toast('Welcome back, '+f.name+'!','ok')}else showErr('lerr','Invalid email or password. Please try again.')},400)}
function doReg(e){e.preventDefault();const nm=document.getElementById('rn').value.trim(),em=document.getElementById('re').value.trim(),pw=document.getElementById('rp').value,cf=document.getElementById('rc').value,b=document.getElementById('rbtn');if(!nm||!em||!pw||!cf){showErr('rerr','Please fill in all fields.');return}if(pw.length<6){showErr('rerr','Password must be at least 6 characters.');return}if(pw!==cf){showErr('rerr','Passwords do not match.');return}b.textContent='Creating Account...';setTimeout(()=>{const us=getUs();b.textContent='Create Account';if(us.some(u=>u.email.toLowerCase()===em.toLowerCase())){showErr('rerr','An account with this email already exists.');return}saveUs([...us,{name:nm,email:em,password:pw}]);const u={name:nm,email:em};saveU(u);updNav(u);closeModal();toast('Account created! Welcome to IIIT Bhopal.','ok')},400)}
function doContact(e){e.preventDefault();const b=document.getElementById('csub');b.textContent='Sending...';b.disabled=true;const d={name:document.getElementById('cn').value,email:document.getElementById('ce').value,subject:document.getElementById('cs').value,message:document.getElementById('cm').value,ts:new Date().toISOString()};const all=JSON.parse(localStorage.getItem('iiitbhopal_contacts')||'[]');all.push(d);localStorage.setItem('iiitbhopal_contacts',JSON.stringify(all));setTimeout(()=>{document.getElementById('fcw').innerHTML='<div class="fsucc"><div class="fsucc-ic">&#10003;</div><h3 class="fsucc-t">Message Sent!</h3><p class="fsucc-d">Thank you for reaching out. Our team will get back to you within 1-2 business days.</p><button class="btn btn-p" onclick="resetCF()">Send Another</button></div>';toast("Message sent! We'll get back to you soon.",'ok')},600)}
function resetCF(){document.getElementById('fcw').innerHTML='<div class="fmt">Send a Message</div><form id="cform" onsubmit="doContact(event)"><div class="frw"><div class="fg2" style="margin-bottom:0"><label class="flb">Full Name <span class="req">*</span></label><input class="fin" id="cn" type="text" placeholder="Your full name" required /></div><div class="fg2" style="margin-bottom:0"><label class="flb">Email <span class="req">*</span></label><input class="fin" id="ce" type="email" placeholder="you@example.com" required /></div></div><div class="fg2"><label class="flb">Subject</label><input class="fin" id="cs" type="text" placeholder="What\'s on your mind?" /></div><div class="fg2"><label class="flb">Message <span class="req">*</span></label><textarea class="fta" id="cm" placeholder="Write your message here..." rows="4" required></textarea></div><button type="submit" class="btn btn-p btn-fw" id="csub">Send Message</button></form>'}
let tt;function toast(m,t){const e=document.getElementById('toast');e.textContent=m;e.className='toast '+(t||'');void e.offsetWidth;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),3500)}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('vis')}),{threshold:.08})
document.querySelectorAll('.fi').forEach(e=>observer.observe(e))
document.getElementById('yr').textContent=new Date().getFullYear()
lucide.createIcons()
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})